project:
  type: book

book:
  title: "Werkzeugbaustein Matplotlib"
  author:
    - Lukas Arnold
    - Simone Arnold
    - Florian Bagemihl
    - Matthias Baitsch
    - Marc Fehr
    - Franca Hollmann
    - Maik Poetzsch
    - Sebastian Seipel
  date: today
  language: de-DE
  downloads: [pdf]
  repo-url: "https://github.com/bausteine-der-datenanalyse/w-python-matplotlib"
  repo-actions: [source]

bibliography: skript/references.bib

format:
  html:
    theme: [cosmo, theme.scss]
    lang: en
    tbl-cap-location: bottom
  pdf:
    documentclass: scrreprt
    lang: en
    toc-depth: 1

execute:
  freeze: auto

profile:
  default: full
  group: 
    - [full, klausur]



